# Welcome to Jekyll!

# Website settings
title: Uğur Tafralı
description: Ugur's blog, use Jekyll and github pages.
keywords: Jack,Jalpc,blog,Jekyll,github,gh-pages
baseurl: ""
url: http://ugurtafrali.com
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog

# author
author:
  name: Uğur Tafralı
  first_name: Uğur
  last_name: Tafralı
  cv: http://cv.ugurtafrali.com
  email: tafraliugur@gmail.com
  facebook_username: 
  github_username: utafrali
  avatar: /static/assets/img/landing/ugurv2.jpeg
  skill_icon1:
    - name: icon-python
    - name: icon-shell
  skill_icon2:
    - name: icon-mongodb
    - name: icon-docker
  desc: I am a Full Stack engineer with website development, automation Ops and writing scripts experience. Life is a continuous learning process, so work makes me more rigorous, travel makes my life more colorful. I can make lots of friends when I coding and travel.

# comment
disqus:
  #name: jalpc
  #public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# analytics
## google analytics
ga:
  #id: UA-93473370-1

go:
  #id: GTM-NHMS8GD

## growingIO
gio:
  # id: a49d4901c7853da9

## donation
donation: off

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
